### ISSUE TITLE
AngelHack (07/18/2015) follow-up

### ISSUE THREAD

**Issue by fiveisprime** [nodeschool/cincinnati#10]
Another successful session! This session was definitely a lot smoother due to
being a lot more prepared.

Now for some stats:
- 23 attendees
- 3 mentors
- New record of exercise 4

The venue brought a lot of people that were ready to get hacking and they
embraced the exercises.
### Things that we should keep doing

We did a much better job of setting up the projector and being ready to go.
### Things that we should start doing

Tara brought up creating a "getting started" section in the main reademe and
direct people to that section. This should have links to all resources (i.e.
the link to the installer and the modules). Getting people into the repository
while they are at the session will be far more effective than just telling
people to visit the repo.
### Things that we can do differently

Get people to the repository and gitter! We're not adding members to the
repository because we aren't getting them there. :(

**Comment by ghost** [comment]
Congrats!  I've had a busy weekend, so I was not able to make it to the
hackathon, however I'm still interested in mentorship.

I wonder how many attendees have accounts to access the repos and gitter?
- Robert Brown

**Comment by jackboberg** [comment]
I like that we had more people actively asking for help than last time, while simultaneously I saw more people working in pairs and helping each other. Probably good that we had a room full of recently caffeinated hackers vs. people getting off work and just finished beer and pizza.

**Comment by tedmiston** [comment]
Hey guys -- from the organizer side, we were really impressed by the format and engagement you guys were able to achieve.  I'd like to see this style catch on in the Python world.  Thanks so much for coming out.
