### ISSUE TITLE
September NodeSchool Session

### ISSUE THREAD

**Issue by tzmanics** [nodeschool/cincinnati#14]
Let's organize a session for September at the Modulus Office (because that seems the easiest/fastest).

I suggest Saturday 9/19 1p for a lunch session or Thursday 9/17 6p for an evening session.

I vote for either `makemehapi` or `test-anything`.

**Comment by fiveisprime** [comment]
Alright, it may be time to create out own meetup group..

**Comment by jackboberg** [comment]
I second `makemehapi`, as we have a local expert and can help educate on new features of `hapi@9.x`

**Comment by tzmanics** [comment]
I've started the making-a-meetup-group process ✌️
The best bet may be to become a sub-group of Node Cincy's meetup group, if they're ok with that. Supposedly that's what CincyPy is to Cincy Tech, I'll look into it.
