### ISSUE TITLE
makemehapi Workshop (10/21/2015)

### ISSUE THREAD

**Issue by tzmanics** [nodeschool/cincinnati#15]
Come join us for the makemehapi workshop at the Modulus offices (1739 Elm St, across from Findlay Market) at 6pm on Wednesday 10/21.

We'll have drinks & snacks as well 🍻

**Comment by jackboberg** [comment]
:+1: Here is the [meetup page](http://www.meetup.com/TechLife-Cincinnati/events/226004156/), if you want to officially RSVP.
