### ISSUE TITLE
wtb logo

### ISSUE THREAD

**Issue by fiveisprime** [nodeschool/cincinnati#2]
Cincinnati NodeSchool needs a logo! Let's come up with something here. :smile:

**Comment by franvarney** [comment]
![cincyns-02b](https://cloud.githubusercontent.com/assets/5891549/8234793/3266209e-15ac-11e5-99b3-dcbc09af7923.png)
![cincyns-02c](https://cloud.githubusercontent.com/assets/5891549/8234794/32669e52-15ac-11e5-9dba-09e86c78b7f1.png)

Colors are irrelevant, they can be anything we want.

Also, these are what I used as references: [http://nodeschool.io/hexdex.html](http://nodeschool.io/hexdex.html)

**Comment by fiveisprime** [comment]
I like the idea of using the airport code (CVG) in place of "CIN" or
"CINCY".

Thoughts on that?

**Comment by jackboberg** [comment]
:+1: on CVG

**Comment by jackboberg** [comment]
other possible icons:
- "Genius of the Water" fountain
- talk stacks boat
- skyline (boring)

**Comment by franvarney** [comment]
I don't think CVG makes sense. Would anyone from another city really understand it?

**Comment by tzmanics** [comment]
Don't know if y'all just heard that but CVG is short for Covington

**Comment by theworkflow** [comment]
Cincinnati Museum Center at Union Terminal really symbolizes the building to me :+1:

**Comment by jackboberg** [comment]
people who travel to/from Cincinnati understand "CVG" for sure

**Comment by tzmanics** [comment]
We could also be pretty to the point and do a nice version of the ohio outline with cincinnati visually signified in some way. 

like this but better, like waaaaay cooler
![image](https://cloud.githubusercontent.com/assets/3611928/8234957/261e0e4a-15ad-11e5-8d05-c86859e8dd33.png)

**Comment by apcomplete** [comment]
+1 on CVG.  Unless we bring back the Nasty Nati.  I like Tall Stacks and Union Terminal best of the ideas for the logo.

**Comment by franvarney** [comment]
But if we were at NodeConf and said CVG, would anyone get it? Covington is a part of the Cincinnati metro area, not the other way around.

**Comment by fiveisprime** [comment]
@tzmanics That would be tough to fit into the NodeSchool hexagon style. Do we
care about that? I like the idea of keeping it consistent with the NodeSchool
"theme" of things.

**Comment by theworkflow** [comment]
I have opinions on both sides to the CVG thing. All nodeschools probably have some things that specific to their people that only they would know. When you google Cincinnati Airport CVG does come up. People traveling to Cincinnati will most likely go through CVG. So I can see the :+1: for that. But on the other hand, it simply doesn't stand for Cincinnati. If we want it to all be Cincinnati then I would say no to it. But CVG is something all Cincinnatians would know about regardless of if they travel or not.

**Comment by franvarney** [comment]
![cincyns-02d](https://cloud.githubusercontent.com/assets/5891549/8235206/ab529fbc-15ae-11e5-8719-c74b1e2a4105.png)

**Comment by anaptfox** [comment]
If we want to represent the entire metro area, CVG is perfect. If we just want to target Cincinnati, It could misleading. 

+1 for Nasty Nati

**Comment by abrongersma** [comment]
I like the Cincy at the bottom personally. Works well with the 5 spokes.

**Comment by jackboberg** [comment]
@lindha is off work next week, and said she will attempt to toss us some other mockups to consider.

@franvarney Can you share your source, so we can maybe try some other color options and you don't have to be solely responsible for answering for everyone's different requests?

**Comment by theworkflow** [comment]
Aw I really like the first logo. I agree with @abrongersma on the logo.

**Comment by fiveisprime** [comment]
Can somebody add some color to @franvarney's design? I'd like to 
add it to the twitter account.

**Comment by fiveisprime** [comment]
Let's call the `CINCY` one it and color it. :metal:

**Comment by tzmanics** [comment]
@franvarney do you have an ai or ps file for this you can share and we can try out options.

@fiveisprime are we calling the deadline for logos today?

**Comment by fiveisprime** [comment]
Deadline is end of the week. I feel weird promoting events with a twitter egg. :hushed:

**Comment by jackboberg** [comment]
I'm still hoping @lindha will find time to try some variations. Per RL conversation, I'd still like to see some text options: (eg: CINTI on top, 513 on bottom?).

@franvarney shared the AI file with me, I'll link up an SVG in a branch for sharing tonight.

**Comment by jackboberg** [comment]
@fiveisprime I have no problem with the idea of using ANY of the options so far until a final is approved by all. Just don't want to do stickers or official stuff without at least seeing a second option.

**Comment by fiveisprime** [comment]
@jackboberg fair enough. Strike that deadline for the final logo and let's get
some more submissions. I would like something by the end of the week to replace
the egg though.

**Comment by ghost** [comment]
any opposition Union Terminal having skinny lines?  possibly no around hexagon?
