### ISSUE TITLE
Nodeschool workshopper request - ACM@UC

### ISSUE THREAD

**Issue by kurtlewis** [nodeschool/cincinnati#21]
Hi everyone,

I've previously spoken with Jack and Tara about doing a nodeschool event/workshopper at an ACM@UC meeting. We had a simple one in mind, say [learnyounode](https://github.com/workshopper/learnyounode). For the most part, the audience would be people with little experience with Javascript.

The exec board was hoping for sometime in late September - we have a meeting on Sept. 22nd at 6pm if that works, but we're definitely flexible. 

Thanks!
Kurt Lewis

**Comment by tzmanics** [comment]
Thanks for kicking this off @lewisku! Thursday Sept. 22 works for me! @jackboberg & @fiveisprime are you two available as well?

What is the setup of the room and about how many people do you think will attend?

Looking forward to this, I haven't been back on UC's campus for over 10 years! Not because they wouldn't let me, I swear 😄

**Comment by kurtlewis** [comment]
We'll probably get a lecture hall with a capacity of 60 or so people, and it'll have at least 1 projector (we'll try for a room with more though). I think a good estimate would be approximately 40 attendees.  You can count on the ACM execs (almost all of us have been to a node cincy meetup by now) to participate however you might need help, mentoring or etc. 

Looking forward to this too!

**Comment by jackboberg** [comment]
I'll plan on attending. Seems like we need 4-6 mentors.
- [x] @tzmanics 
- [x] @jackboberg
- [ ] @fiveisprime 
- [x] @franvarney
- [x] @musgravejw
- [ ] @harlanj

**Comment by franvarney** [comment]
✋

**Comment by musgravejw** [comment]
👍

**Comment by kurtlewis** [comment]
Hi Everyone!

Just following up with a few more details! 

We've reserved a room, CRC 3220, for Thursday Sept 22nd at 6:00pm. Its centrally located on campus, and you can get there from [the stairs directly across from the mainstreet starbucks](https://www.google.com/maps/place/39%C2%B007'56.6%22N+84%C2%B030'56.9%22W/@39.1323831,-84.516912,18z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d39.132381!4d-84.515815). The room we'll be in is a lecture hall with a capacity of about 70, though we expect closer to 40 students. The room has 3 projectors. It has a computer I can log you into if need be, and a VGA hookup for a laptop. 

Let's plan on doing the learnyounode workshopper if that works for you! We'll keep the actual workshopper to about an hour, so we can just do as much as we can in that time. ACM Execs can help with technical issues and general mentor ship as need be.

We'll have food, so come hungry! 

As for parking, I'd recommend [Woodside, University Avenue, or Campus Green garages](https://www.uc.edu/parking/visitors-maps.html#wa)

Let me know if you have any questions or think I've forgotten anything!

Thanks,

Kurt

**Comment by tzmanics** [comment]
Thanks for the info Kurt! I _can_ make a meetup but w/ 40 people already coming it's probably best to just keep it going through ACM@UC. Although the room can hold 70 we'll have a much easier time working/teaching w less.

`learnyounode` is a good workshopper. It does have 13 exercises but we're really comfortable with that one & I think it's a fun one to teach too! We can always just see how far we get and let people finish on their own time or we can only allot a certain amount of time to each exercise to make sure we cover them all. Sometimes people feel rushed in the latter scenario though. Do you all have a preference?

**Comment by kurtlewis** [comment]
Sorry, I saw this but never actually realized there was a question at the end! Let's just plan on getting as far as we can, and then letting people finish on their own if we don't finish.

**Comment by tzmanics** [comment]
Sounds good @lewisku! 

Please feel free to send attendees the link to the repo homepage if they need help getting setup for the workshop: https://github.com/nodeschool/cincinnati

Do you think there will be many people needing help with getting their environment setup? Should I/we come a little early (~5:30) in case people need hands-on help?

**Comment by kurtlewis** [comment]
There are definitely going to be people who don't have Node installed, so I was planning on having instructions for that going as people come in. ACM@UC will have a short presentation of updates on the organization, and people can install while I go over that. Most people won't show up until about 6, so I'm afraid being there early won't do much good. That being said, I'll be in the room as soon as its free, so arriving anytime between 5:30 to 6 is fine. 

And thanks! I'll include a link to the repo homepage.

**Comment by tzmanics** [comment]
Cool! see you soon!

**Comment by kurtlewis** [comment]
Thank you everyone for coming out last night! We appreciate it and hope you had as much fun as we did!
