### ISSUE TITLE
Node.Cincy (07/08/2015)

### ISSUE THREAD

**Issue by fiveisprime** [nodeschool/cincinnati#4]
We'll be doing a NodeSchool session for [Node.Cincy on July 8th](http://www.meetup.com/Node-cincy/events/222512181). Let me know if
you can't make the 8th. :)

This is what I have so far for the blurb on the Meetup page. Let me know what
you think and definitely let me know if I missed something.

> The Cincinnati NodeSchool chapter will be running a workshop for this month's
> Node.Cincy! The workshop includes running through guided examples with the
> organizers of Cincinnati NodeSchool present to help with any questions or
> issues.
> 
> This is open to everybody who wants to learn Node.js - no prior Node.js
> experience is required. The [workshopper](https://github.com/workshopper/workshopper) is a Node.js terminal application so
> bring your laptop with Node.js installed. If you aren't able to get Node.js
> installed, come early and one of the mentors can help get you up and running.
> Don't have a laptop? Pair up with somebody and make a new friend while
> you learn. :)
> 
> The [Cincinnati NodeSchool repository](https://github.com/nodeschool/cincinnati) will be available for any questions you
> might have before or after the workshop. Open an issue with your question and
> we'll do our best to help.
> 
> There is a code of conduct for this and all Cincinnati NodeSchool events, which
> is available in the [Cincinnati NodeSchool repository](https://github.com/nodeschool/cincinnati/blob/master/code_of_conduct.md)

**Comment by jackboberg** [comment]
:shipit:

**Comment by tzmanics** [comment]
👍Thanks, Matt 👍
👏

**Comment by fiveisprime** [comment]
The meetup details are updated with the workshop information, thanks for the
feedback and help.

http://www.meetup.com/Node-cincy/events/222512181/

**Comment by anaptfox** [comment]
Is there a reason it's at the Brandery? Instead of the Modulus office.

**Comment by fiveisprime** [comment]
They have a better place to hack - tables and desk chairs in the second floor
area. That and pizza can actually be delivered there haha

**Comment by anaptfox** [comment]
That's fair. lol 👍

**Comment by fiveisprime** [comment]
This session will be [learnyounode](https://www.npmjs.com/package/learnyounode) with somebody (probably me) running through
the exercises and explaining how the workshopper works on the TV. Let's do an
exercise then give people time to work through it on their own (with mentors
helping where needed) and get through as many as we can in about an hour (maybe
more?)

I'd say we plan the first 30-45 minutes for helping people get Node.js setup
and the module installed (19h00-19h45) followed by an hour of workshopper
(19h45-20h45) then break into social time. That should keep people from getting
overwhelmed and keep the atmosphere light.

**Comment by tzmanics** [comment]
super 👍should we wear our nodeconf or modulus shirts to distinguish the mentors (orange or green for easy visibility 😏)

**Comment by fiveisprime** [comment]
See #6
