### ISSUE TITLE
General Promotion Questions

### ISSUE THREAD

**Issue by tzmanics** [nodeschool/cincinnati#5]
Was about to tweet about the meetup and realized we should agree on a hashtag.
cincinodeschool
nodeschoolcinti
...
?

**Comment by jackboberg** [comment]
I think we could probably just use #nodeschool. Would allow the greater community to follow along.

**Comment by jackboberg** [comment]
When referring to our instance specifically, we can use @CincyNodeSchool.

**Comment by theworkflow** [comment]
I think we should still have our own hashtag on top of the twitter handle. Would bring out our name more but still note that we're part of the nodeschool community

**Comment by anaptfox** [comment]
Just use both in combination. #nodeshool and #cinci. I think it accomplishes both goals.

**Comment by tzmanics** [comment]
It seems the consensus is using #nodeschool and @NodeSchoolCincy along with any other fun local tags like #cinci & #cincytech etc.
