### ISSUE TITLE
Tutorial request for AngelHack Cincinnati

### ISSUE THREAD

**Issue by tedmiston** [nodeschool/cincinnati#7]
Hey guys,

I had a short conversation with Tara this morning about how presenting the Node School tutorial given at The Brandery last night (or another if you'd a different one more relevant) to our audience at AngelHack Cincinnati 2015 on Saturday, July 18.

We are flexible on timing on Saturday and would really like to have Modulus at the event.  I can answer any questions here.

Event info page - https://www.eventbrite.com/e/angelhack-cincinnati-2015-tickets-15569299193

Thank you,
Taylor

**Comment by tzmanics** [comment]
I think this is a great idea! @tedmiston check out this site (http://nodeschool.io/#javascripting) for all the different workshoppers we do (we did the intro one: learnyounode at the Brandery) and see if one seems more relevant to the crowd.

Personally earlier on Saturday works best for me (I have to head to Louisville for a show). Do you think there's a time in the schedule it would work better i.e. before the hackathon starts or after?

**Comment by fiveisprime** [comment]
I'm so up for this, I'll see what other mentors are available and do you have
an idea of what attendance looks like for AngelHack so far? I want to make sure
that we keep the attendee:mentor ratio high balanced.

**Comment by tedmiston** [comment]
@tzmanics @fiveisprime 

Workshop - I think either `learnyounode` or `javascripting` would be great.  Roughly how long did it take to present?

Timing - We can flex the schedule to do it as early as 11:30 before the hackathon starts at noon, or we could adjust the hackathon start time slightly.

Attendance - As of right now we have 73 tickets sold (subtract 9 for judges), and we expect 50% attrition.  Our goal is to get the total number up to 100-150 between now and the event.  One or two mentors would be great, but more help is always awesome.

Jay Clouse, who is very active at Startup Weekend events in Columbus / working at Tixers, will also be mentoring on Saturday.  Anyone is welcome to come out for final presentations on Sunday as well.

-T

**Comment by ghost** [comment]
@tedminston

i would like to be a mentor for nodeschool at the hackathon.  is there a
formal signup page?
- Robert Brown

**Comment by fiveisprime** [comment]
@tedmiston The workshop runs for a maximum of two hours before people start
getting burned out. One hour is a good amount of time to get people going - the
workshops are doable solo.

I remember last year's AngelHack had really short sessions (I ended up in the
famous session with Ry) which may not be enough time to get in super deep. That
said, maybe we could do the `learnyounode` or `stream-adventure` both of which
get into fun stuff pretty quickly.

@robertBrown send me an email about being a mentor :)

**Comment by tedmiston** [comment]
@fiveisprime Yeah, one hour would be great.  I think last year's were half hour or one hour (@ryw might remember)?

Both sound cool.  Which one do you think would be more accessible for an audience with a decent amount of students and entry-level devs?

**Comment by fiveisprime** [comment]
Sounds like `learnyounode` would be best then.

I'll create a new issue for the event so we can start planning things.

Thanks!

**Comment by tedmiston** [comment]
Awesome.  Thanks, Matt.

**Comment by ryw** [comment]
Pretty sure Gerard did an hour on Meteor - but was that two years ago?
I'd stick to 30-40 minutes max.
