### ISSUE TITLE
AngelHack (07/18/2015)

### ISSUE THREAD

**Issue by fiveisprime** [nodeschool/cincinnati#8]
Presentation starts at 11h30 at [UpTech](https://www.google.com/maps/place/112+W+Pike+St,+Covington,+KY+41011/data=!4m2!3m1!1s0x8841b1375202f6ed:0x92b041d206f5e473?sa=X&ei=MvCfVZTfIIeUyASR74zIAg&ved=0CB4Q8gEwAA). We'll be running the learnyounode
workshop and we'll have an hour to get through as much as possible.

The [AngelHack](https://www.eventbrite.com/e/angelhack-cincinnati-2015-tickets-15569299193) event is pretty big, but not everybody will be interested in
joining. I would expect no more than about 25 or so to show for the workshop.

Mentors, let me know who is available so I can get you on this list. :) Anybody
else that would like to be a mentor, comment here and I'll get you added.
- Matt Hernandez - @fiveisprime
- Jack Boberg - @jackboberg
- Tara Z. Manicsic - @tzmanics

I'll keep this comment update with answers to any other questions that come up.

Related to #7

**Comment by tedmiston** [comment]
@fiveisprime This looks perfect.  I'll have our official schedule updated to include it.  Thanks so much.

**Comment by fiveisprime** [comment]
@tedmiston can you change the schedule to be NodeSchool rather than a
Modulus run event?

**Comment by tedmiston** [comment]
@fiveisprime Sure, I just changed it on hackathon.io. I'll have AngelHack update the schedule on Eventbrite.

**Comment by fiveisprime** [comment]
Awesome, thanks!

**Comment by tedmiston** [comment]
@fiveisprime @jackboberg @tzmanics You guys are welcome to show up anytime tomorrow to setup (doors officially open at 9 am).  Also, feel free to stick around the rest of the day to help mentor or volunteer, and of course to grab some lunch.  Thanks again.

The official schedule for reference - http://www.hackathon.io/events/2437

**Comment by fiveisprime** [comment]
See #10
