### ISSUE TITLE
LearnYouNode Issue: Navigating between exercises

### ISSUE THREAD

**Issue by jhlink** [nodeschool/cincinnati#9]
Instead of calling LearnYouNode all the time to get to various exercises, could we add functionality like executing "learnyounode next/prev/X" where X is some exercises number for fast navigation?

**Comment by ghost** [comment]
need more clarity.  so you're saying to provide an option to execute the
workshopper without a Graphical User Interface?
- Robert Brown

**Comment by jackboberg** [comment]
Good feedback, but I think this feature request belongs on the [workshopper](https://github.com/workshopper/workshopper) module. That is what _most_ of the workshoppers are built with, and it would need to be implemented at that level.

**Comment by jackboberg** [comment]
I just checked, and `> learnyounode next` is already implemented. :+1:
